import mongoose, { Schema, Document } from "mongoose";

export interface IMockTest extends Document {
  id: string;
  title: string;
  slug: string;
  description?: string;
  examType: "NEET" | "JEE" | "BOTH";
  testType: "full" | "subject";
  subjectId?: string | null;
  subject?: string | null;
  difficulty?: string;
  startDate?: Date | null;
  endDate?: Date | null;
  generationMode: "fixed" | "automatic";
  generationFrequency: "daily";
  generationTime?: string;
  isGenerationTemplate: boolean;
  parentTemplateId?: string | null;
  lastScheduledGenerationKey?: string;
  isOneTimeFree: boolean;
  patternPreset: "NEET_REAL" | "JEE_REAL" | "CUSTOM";
  durationMinutes: number;
  totalQuestions: number;
  maxScore: number;
  questionIds: string[];
  subjectIds: string[];
  chapterIds: string[];
  topicIds: string[];
  instructions: string[];
  marksPerQuestion: number;
  negativeMarks: number;
  markingSchemeVersion?: string;
  markingScheme?: Record<string, unknown>;
  questionMarkingRules: Array<Record<string, unknown>>;
  markingOverrideEnabled: boolean;
  predictionTitle?: string;
  predictionDescription?: string;
  availabilityMode: "all" | "day_wise" | "week_wise";
  availableDaysOfMonth: number[];
  availableWeekdays: string[];
  totalAttemptQuestions?: number;
  sectionGroups: Array<Record<string, unknown>>;
  generationSource: "manual" | "auto";
  generationScheduleType?: "daily" | "weekly" | "monthly" | "manual" | "";
  generationConfig?: Record<string, unknown>;
  generationHistory: Array<Record<string, unknown>>;
  selectionMix?: Record<string, unknown>;
  includedQuestionIds: string[];
  randomizeQuestionOrder: boolean;
  freeAccessDurationValue: number;
  freeAccessDurationUnit: "days" | "weeks" | "months";
  premiumDurationType: "daily" | "weekly" | "monthly";
  premiumValidityDays: number;
  autoDailyQuestionRearrangement: boolean;
  autoDailyQuestionGeneration: boolean;
  lastAutoGeneratedDateKey?: string;
  isPremiumOnly: boolean;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const MockTestSchema = new Schema<IMockTest>(
  {
    title: { type: String, required: true, trim: true },
    slug: { type: String, required: true, trim: true, unique: true, index: true },
    description: String,
    examType: { type: String, enum: ["NEET", "JEE", "BOTH"], required: true, index: true },
    testType: { type: String, enum: ["full", "subject"], default: "full", index: true },
    subjectId: { type: String, default: null, index: true },
    subject: { type: String, trim: true, default: null },
    difficulty: { type: String, trim: true, default: "mixed" },
    startDate: { type: Date, default: null },
    endDate: { type: Date, default: null },
    generationMode: { type: String, enum: ["fixed", "automatic"], default: "fixed", index: true },
    generationFrequency: { type: String, enum: ["daily"], default: "daily" },
    generationTime: { type: String, default: "00:00" },
    isGenerationTemplate: { type: Boolean, default: false, index: true },
    parentTemplateId: { type: String, default: null, index: true },
    lastScheduledGenerationKey: { type: String, default: "" },
    isOneTimeFree: { type: Boolean, default: false, index: true },
    patternPreset: { type: String, enum: ["NEET_REAL", "JEE_REAL", "CUSTOM"], default: "CUSTOM", index: true },
    durationMinutes: { type: Number, required: true, min: 1 },
    totalQuestions: { type: Number, required: true, min: 1 },
    maxScore: { type: Number, required: true, min: 1 },
    questionIds: { type: [String], default: [] },
    subjectIds: { type: [String], default: [] },
    chapterIds: { type: [String], default: [] },
    topicIds: { type: [String], default: [] },
    instructions: { type: [String], default: [] },
    marksPerQuestion: { type: Number, default: 4 },
    negativeMarks: { type: Number, default: 1 },
    markingSchemeVersion: { type: String, default: "v1" },
    markingScheme: { type: Schema.Types.Mixed },
    questionMarkingRules: { type: [Schema.Types.Mixed], default: [] },
    markingOverrideEnabled: { type: Boolean, default: false },
    predictionTitle: String,
    predictionDescription: String,
    availabilityMode: { type: String, enum: ["all", "day_wise", "week_wise"], default: "all" },
    availableDaysOfMonth: { type: [Number], default: [] },
    availableWeekdays: { type: [String], default: [] },
    totalAttemptQuestions: { type: Number, min: 1 },
    sectionGroups: { type: [Schema.Types.Mixed], default: [] },
    generationSource: { type: String, enum: ["manual", "auto"], default: "manual", index: true },
    generationScheduleType: { type: String, enum: ["daily", "weekly", "monthly", "manual", ""], default: "", index: true },
    generationConfig: { type: Schema.Types.Mixed },
    generationHistory: { type: [Schema.Types.Mixed], default: [] },
    selectionMix: { type: Schema.Types.Mixed },
    includedQuestionIds: { type: [String], default: [] },
    randomizeQuestionOrder: { type: Boolean, default: true },
    freeAccessDurationValue: { type: Number, default: 1, min: 1 },
    freeAccessDurationUnit: { type: String, enum: ["days", "weeks", "months"], default: "days" },
    premiumDurationType: { type: String, enum: ["daily", "weekly", "monthly"], default: "daily" },
    premiumValidityDays: { type: Number, default: 1, min: 1 },
    autoDailyQuestionRearrangement: { type: Boolean, default: false },
    autoDailyQuestionGeneration: { type: Boolean, default: false },
    lastAutoGeneratedDateKey: { type: String, default: "" },
    isPremiumOnly: { type: Boolean, default: false, index: true },
    isActive: { type: Boolean, default: true, index: true },
  },
  {
    timestamps: true,
    toJSON: {
      virtuals: true,
      transform: (_doc, ret) => {
        ret.id = ret._id?.toString();
        delete ret._id;
        delete ret.__v;
        return ret;
      },
    },
  },
);

MockTestSchema.index({ examType: 1, isActive: 1, createdAt: -1 });
MockTestSchema.index({ testType: 1, examType: 1, subjectId: 1, isActive: 1 });

export const MockTest =
  mongoose.models["MockTest"] ?? mongoose.model<IMockTest>("MockTest", MockTestSchema);
