import mongoose, { Schema, Document } from "mongoose";

export interface IRevisionSettings extends Document {
  id: string;
  wrongQuestionLimit: number;
  oldQuestionLimit: number;
  dailyRevisionLimit: number;
  revisionEnabled: boolean;
  includeWrongQuestions: boolean;
  includeSkippedQuestions: boolean;
  includeLowAccuracyQuestions: boolean;
  includeWeakAreaQuestions: boolean;
  accuracyThreshold: number;
  minimumCorrectAnswers: number;
  completionAttemptCount: number;
  difficultyMode: "easy" | "medium" | "moderate" | "hard" | "mixed";
  scheduleMode: "daily" | "weekly" | "custom";
  autoGeneratedRevisionTests: boolean;
  customRevisionQuestionIds: string[];
  subjectSettings?: Record<string, unknown>;
  chapterSettings?: Record<string, unknown>;
  topicSettings?: Record<string, unknown>;
  spacedDays: number[];
  createdAt: Date;
  updatedAt: Date;
}

const RevisionSettingsSchema = new Schema<IRevisionSettings>(
  {
    wrongQuestionLimit: { type: Number, default: 10, min: 1, max: 100 },
    oldQuestionLimit: { type: Number, default: 5, min: 1, max: 100 },
    dailyRevisionLimit: { type: Number, default: 20, min: 1, max: 200 },
    revisionEnabled: { type: Boolean, default: true },
    includeWrongQuestions: { type: Boolean, default: true },
    includeSkippedQuestions: { type: Boolean, default: true },
    includeLowAccuracyQuestions: { type: Boolean, default: true },
    includeWeakAreaQuestions: { type: Boolean, default: true },
    accuracyThreshold: { type: Number, default: 80, min: 0, max: 100 },
    minimumCorrectAnswers: { type: Number, default: 1, min: 0, max: 200 },
    completionAttemptCount: { type: Number, default: 1, min: 1, max: 20 },
    difficultyMode: { type: String, enum: ["easy", "medium", "moderate", "hard", "mixed"], default: "mixed" },
    scheduleMode: { type: String, enum: ["daily", "weekly", "custom"], default: "daily" },
    autoGeneratedRevisionTests: { type: Boolean, default: true },
    customRevisionQuestionIds: { type: [String], default: [] },
    subjectSettings: { type: Schema.Types.Mixed, default: {} },
    chapterSettings: { type: Schema.Types.Mixed, default: {} },
    topicSettings: { type: Schema.Types.Mixed, default: {} },
    spacedDays: {
      type: [Number],
      default: [1, 2, 5, 10],
      validate: {
        validator: (value: number[]) =>
          Array.isArray(value) && value.length > 0 && value.every((day) => Number.isFinite(day) && day > 0),
        message: "spacedDays must contain one or more positive numbers",
      },
    },
  },
  {
    timestamps: true,
    collection: "revisionsettings",
    toJSON: {
      virtuals: true,
      transform: (_doc, ret) => {
        ret.id = ret._id?.toString();
        delete ret._id;
        delete ret.__v;
        return ret;
      },
    },
  },
);

export const RevisionSettings =
  mongoose.models["RevisionSettings"] ?? mongoose.model<IRevisionSettings>("RevisionSettings", RevisionSettingsSchema);
